### ISSUE TITLE
Agregar una animación o foto a la pantalla principal del proyecto 

### ISSUE THREAD

**Issue by delciopolanco** [Roliver-Javier/blogyager#2]
Quiero poder ver una animacion o foto del uso de este proyecto, y como puede beneficiarme por utilizarlo.

Ejemplo: https://github.com/AdityaSoni19031997/CNN-from-Scratch

**Comment by Roliver-Javier** [comment]
Done!

**Comment by Roliver-Javier** [comment]
Done!, Thanks.
